apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-ui
spec:
  template:
    spec:
      containers:
        - name: platform-ui
          resources:
            requests:
              memory: "100Mi"
            #             cpu: "100m"
            limits:
              memory: "500Mi"
