apiVersion: v1
kind: Secret
metadata:
    name: example
    annotations:
        argocd.argoproj.io/hook: PreSync
        argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
type: Opaque
data:
    username: ENC[AES256_GCM,data:i2sbw+H/4IY=,iv:7oVBtq42JgPczlvkD1Mo1ZeFtLvzyEG/XTm4mG3jOAk=,tag:FJ4Xb7PlrgTjyCPgy+ZnMQ==,type:str]
    password: ENC[AES256_GCM,data:awkU0dMzqjSDC8siYsM8ig==,iv:EK7pLUu5gIGBYFMOMNXAjdkmhp0+5VwSCKdPj6s6xZA=,tag:WAHbD0mRG3a5X2Jv5ipM4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-03-13T20:35:17Z"
    mac: ENC[AES256_GCM,data:TkB9kXBighr1ukEJcm7Eiy2r0cxOybAmdpxU/U8vv9HeDiKArcBKfnFsNw2YykU9Hisfta4m4yqUXNifh+Mey5YuufCmbHvyoMly4ZXdcSj7BzXNZ18UgbFQAEb17eDMe1TNNfJQaJG8uKYEOy6kPQWpXOG4bLH5dJkTN4IiFcc=,iv:WZujrMso9E76Fip2Lwo3iCdagCa+Z0dnK6pdKmM4nHM=,tag:xZBzjGcqgA/UIhmP4jY14g==,type:str]
    pgp:
        - created_at: "2024-03-13T20:35:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DvpJeLmD3UrYSAQdAowD2kpAH/xZADcXBUuXgr+/TSxR5OjiGxKgrvz2JoVsw
            Z10uHNtummeePXvdV6ng1A8qZbqUZOmerpMDty9pE5r/8MImv5SiniAdnP57EpGc
            0lwBP/Qc6SPlzwmfCWMsz3Yw8yG3vuC5d61t1fb+c0wbQGS0oPjnlTrPwcHnDh9p
            +vAJB36f3e/Mta4mWOr2Axvmuf+hqChqsNqxbVs0H+7HV0VOOn37yJPZODXG7g==
            =744T
            -----END PGP MESSAGE-----
          fp: D5B2CEFC1C54A4F373475349C4CCE331E8DB5CD7
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
