apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- platform-api.deployment.yml
- platform-api.service.yml
- platform-api.hpa.yml
- migrations/migration_job.yml

images:
- name: ghcr.io/theopenshelf/platform-api
  newTag: 0.0.86
