apiVersion: v1
kind: Service
metadata:
  name: platform-api
  labels:
    app: platform-api
    spring-boot: "true"

spec:
  type: NodePort
  selector:
    app: platform-api
  ports:
    - port: 80
      targetPort: http-server
      nodePort: 30081
