apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- platform-ui.deployment.yml
- platform-ui.service.yml
- platform-ui.hpa.yml

images:
- name: ghcr.io/theopenshelf/platform-ui
  newTag: 0.0.61
