apiVersion: v1
kind: Service
metadata:
  name: platform-ui
  labels:
    app: platform-ui
    spring-boot: "true"

spec:
  type: ClusterIP
  selector:
    app: platform-ui
  ports:
    - port: 80
      targetPort: http-server
