apiVersion: v1
kind: Service
metadata:
  name: platform-ui
  labels:
    app: platform-ui
spec:
  type: NodePort
  selector:
    app: platform-ui
  ports:
    - port: 80
      targetPort: http-server
      nodePort: 30085
