apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-ui
  labels:
    app: platform-ui
spec:
  selector:
    matchLabels:
      app: platform-ui
  template:
    metadata:
      labels:
        app: platform-ui
      annotations:
        prometheus.io/path: /
        prometheus.io/port: "80"
        prometheus.io/scrape: "true"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - platform-ui
                topologyKey: "kubernetes.io/hostname"

      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: platform-ui
          image: ghcr.io/theopenshelf/platform-ui
          imagePullPolicy: Always
          ports:
            - name: http-server
              containerPort: 80
          env:
            - name: PORT
              value: "80"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 300
            periodSeconds: 5
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 2
            httpGet:
              path: /
              port: 80
