apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-api
spec:
  template:
    spec:
      containers:
        - name: platform-api
          resources:
            requests:
              memory: "800Mi"
              cpu: "300m"
            limits:
              memory: "1000Mi"
